### ISSUE TITLE
IconData should derive common functionality

### ISSUE THREAD

**Issue by lpotthast** [Carlosted/icondata#2]
IconData is a public item and does not derive anything. It should at least derive `Debug`.
It could probably safely
```
#[derive(Debug, PartialEq, Eq, Clone, Copy)]
```

**Comment by Carlosted** [comment]
can you take at my answer about this: https://github.com/Carlosted/leptos-icons/issues/13.

I think you are right and we could derive these functionalities safely.

Do you think serde should be derived for individual icon enums, or only for `IconData`?

**Comment by Carlosted** [comment]
Big refactoring is in the way, I will make this change along with more stuff.
